name: Java CI with Maven

on:
  push:
    branches: ["master"]
env:
  REPO_NAME: simple-java-maven-app
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: docker build -t sava128/${{ env.REPO_NAME }}:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push sava128/${{ env.REPO_NAME }}:${{ github.sha }}

  deploy:
    needs: build-and-publish
    name: deploy image
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy Docker image to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          docker pull sava128/${{ env.REPO_NAME }}:${{ github.sha }}
          docker stop $(docker ps -a -q) || true
          docker run -d -p 80:80 sava128/${{ env.REPO_NAME }}:${{ github.sha }}
          EOF
